module.exports = {
    CATEGORY_LIST_REQUEST : 'CATEGORY_LIST_REQUEST',
    CATEGORY_LIST_SUCCESS : 'CATEGORY_LIST_SUCCESS',
    CATEGORY_LIST_FAIL : 'CATEGORY_LIST_FAIL', 

    CATEGORY_UPDATE_REQUEST : 'CATEGORY_UPDATE_REQUEST',
    CATEGORY_UPDATE_SUCCESS : 'CATEGORY_UPDATE_SUCCESS',
    CATEGORY_UPDATE_FAIL : 'CATEGORY_UPDATE_FAIL', 

    CATEGORY_SAVE_REQUEST : 'CATEGORY_SAVE_REQUEST',
    CATEGORY_SAVE_SUCCESS : 'CATEGORY_SAVE_SUCCESS',
    CATEGORY_SAVE_FAIL : 'CATEGORY_SAVE_FAIL', 

    CATEGORY_DELETE_REQUEST : 'CATEGORY_DELETE_REQUEST',
    CATEGORY_DELETE_SUCCESS : 'CATEGORY_DELETE_SUCCESS',
    CATEGORY_DELETE_FAIL : 'CATEGORY_DELETE_FAIL',
}